# Generated by Django 3.2.5 on 2024-08-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('code_cate', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cate', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idCli', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('prenom', models.CharField(blank=True, max_length=150, null=True)),
                ('adresse', models.CharField(blank=True, max_length=150, null=True)),
                ('télé', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('cin', models.CharField(blank=True, max_length=20, null=True)),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('prenom', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=128)),
                ('télé', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('code_Souscate', models.AutoField(primary_key=True, serialize=False)),
                ('nom_sous_cate', models.CharField(blank=True, max_length=150, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('idProd', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('prix', models.FloatField(blank=True, null=True)),
                ('qteTotal', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categorie')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
