# Generated by Django 3.2.5 on 2024-08-16 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscategorie',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscategories', to='myapp.categorie'),
        ),
    ]
