# Generated by Django 3.2.5 on 2024-08-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_souscategorie_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='sousCategorie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.souscategorie'),
        ),
    ]
