# Generated by Django 3.2.5 on 2024-08-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_cart_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
    ]
